version: '3'

services:
  db:
    image: postgres:15.1-alpine3.17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: workdb123
      POSTGRES_USER: postgres
      POSTGRES_DB: work_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@erwin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - servidor
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - 3001:3001
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - frontend
  # Bom configurar o kafka em outro docker-compose.yml
networks:
  servidor:
    # Deixa asssim, só remove se atrapalhar em algo, é pro kafka
    driver: bridge
  frontend:
volumes:
  pgdata:
  backend:
  frontend:
