version: '3'

services:
  db:
    image: postgres:15.1-alpine3.17
    networks:
      - my-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: workdb123
      POSTGRES_USER: postgres
      POSTGRES_DB: work_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@erwin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - my-network
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=workdb123
      - FRONT_URL=http://frontend:3000
      - DB_NAME=work_db
      - JWT_SECRET=secret
      - JWT_EXPIRATION=864000
    networks:
      - my-network

     

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/apps
    environment:
      - BACKEND_URL=http://backend:3001
    restart: always
    depends_on:
      - backend
    networks:
      - my-network

      
  # Bom configurar o kafka em outro docker-compose.yml
networks:
    my-network:
      driver: bridge
volumes:
  pgdata:
  backend:
  frontend: