version: '3'
services:
  backend:
    build: ./backend
    ports:
      - # nao sei os ports
    links:
      - db
  frontend:
    build: ./frontend
    ports:
      - # nao sei ainda
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
